version: '3.8'

services:
  db:
    image: postgres:14.2
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: user_post_service
      SCHEMA: public
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    command: npm run start:dev
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/user_post_service?schema=public&sslmode=disable
      JWT_SECRET: 01JWEYXKTQA005MDNHTH4VM2QE
      JWT_EXPIRATION: 1200
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - path: ./src
          action: sync
          target: /usr/src/app/src
        - path: ./prisma
          action: sync
          target: /usr/src/app/prisma
        - path: package.json
          action: rebuild
        - path: package-lock.json
          action: rebuild
        - path: Dockerfile
          action: rebuild

volumes:
  db_data:
